### ISSUE TITLE
es crashing whole session when multiple models are specified

### ISSUE THREAD

**Issue by PetoLau** [config-i1/smooth#101]
Hi,
I am trying to fit seasonal ES model with additional xreg vector. When I am trying to fit ES with only one model option (for example "AAA") it is working. But when multiple models are tried (c("AAA", "ANA")) it crashes whole r session.

Code:
`library(smooth)`
`freq <- 48`
`h <- 2`
`data_ts <- ts(Y, freq = freq * 7)`
`meteo_all <- c(meteo, meteo_test)`
`pred <- es(data_ts, model = c("AAA", "ANA"), ic = "AIC", h = h, xreg = meteo_all, cfType = "MAE", intervals = "none", silent = "all")$forecast`

Data:
[test.zip](https://github.com/config-i1/smooth/files/1575683/test.zip)

Thanks for any suggestions.
Peter

**Comment by config-i1** [comment]
Looks like bug. I'll investigate.
Thanks!

**Comment by config-i1** [comment]
Unfortunately I cannot reproduce this bug in the latest version of smooth (from github) on my PC. Can you, please, provide the following details about your configuration:
1. R version;
2. smooth version;
3. Operating System type.

**Comment by PetoLau** [comment]
1. R version 3.4.3 (2017-11-30)
2. smooth_2.2.1
3. Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
So Windows 10.

**Comment by config-i1** [comment]
Just to check, does the same error appear when you use smooth from github?
You can install it via:
> if (!require("devtools")){install.packages("devtools")}
> devtools::install_github("config-i1/smooth")

**Comment by PetoLau** [comment]
Hm...no, it does not crash.

**Comment by config-i1** [comment]
Great! I've fixed some bugs in the latest version, so maybe that was one of them :)
