### ISSUE TITLE
Error in if (any(c(orders) < 0)) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by andreykirson** [config-i1/smooth#110]
Try to call ges() function but get the follow error: 
```
fit_ges <- ges(p_with_restore_values$Qty, oders=c(1,1,1), lags = c(1,7,365), transition = diag(3), measurement = c(1,1,1))
Error in if (any(c(orders) < 0)) { : 
  missing value where TRUE/FALSE needed
```

**Comment by config-i1** [comment]
You are missing letter "r" in the word "orders". The following should work:

fit_ges <- ges(p_with_restore_values$Qty, orders=c(1,1,1), lags = c(1,7,365), transition = diag(3), measurement = c(1,1,1))
