### ISSUE TITLE
Warning message: xreg contained too many observations, so we had to cut off some of them.

### ISSUE THREAD

**Issue by andreykirson** [config-i1/smooth#111]
Имеется временной ряд, который имеет сезонность по дням недели. Временной ряд состоит из 158 наблюдений. Дополнительно имеется вектор экзогенной переменной 158 значений + 21 значение для которых необходимо построить прогноз.

```
`> xreg_model_trimed <- es(ts(Data_for_xreg_trimed2$Qty, frequency = 7, start = 1), "ZZA", xreg = Price_for_xreg, intervals = "np")`

Warning message:
xreg contained too many observations, so we had to cut off some of them.
```

При попытке нарисовать прогноз 
`>plot(forecast(xreg_model_trimed, h=21))`

Получаю следующее сообщение:
```
Warning message:
xreg did not contain values for the holdout, so we had to predict missing values.
```

Если добавляю параметр holdout = TRUE , то получаю следующее. График соответственно никакой не рисуется. 

```
> xreg_model_trimed <- es(ts(Data_for_xreg_trimed2$Qty, frequency = 7, start = 1), "ZZA", xreg = Price_for_xreg, intervals = "np", holdou=TRUE)

> xreg_model_trimed <- es(ts(Data_for_xreg_trimed2$Qty, frequency = 7, start = 1), "ZZA", xreg = Price_for_xreg, intervals = "np", holdou=TRUE)
Warning message:
xreg contained too many observations, so we had to cut off some of them. 
> plot(forecast(xreg_model_trimed, h=21))
Warning messages:
1: xreg did not contain values for the holdout, so we had to predict missing values. 
2: Negative values produced in the level of state vector of model MNA.
We had to substitute them by low values. Please, use a different model. 
```

**Comment by config-i1** [comment]
В первой строке надо задать горизонт прогнозирования - "h=21" - иначе функция обрезает последние 11, считая их ненужными.
Во второй строке модель уже содержит на 11 наблюдений меньше, и вы просите её дать прогноз на больший период, поэтому она пропущенные значения экстраполирует.
В третьей части в слове "holdout" пропущена буква "t". Более того в этом случае функция видит, что в ваших регрессорах на 21 значение больше, чем нужно и обрезает их. Когда же в делаете прогноз, экзогенных переменных уже нет, поэтому опять модель их экстраполирует.

В общем, решается это всё вот так:
`xreg_model_trimed <- es(ts(Data_for_xreg_trimed2$Qty, frequency = 7, start = 1), "ZZA", xreg = Price_for_xreg, intervals = "np", h=21, silent=FALSE)`

О нюансах работы с функцией в случае с экзогенными переменными, я писал тут: https://forecasting.svetunkov.ru/2018/01/15/xreg-basics/
