### ISSUE TITLE
fitted confidence intervals for sma()?

### ISSUE THREAD

**Issue by shuckle16** [config-i1/smooth#123]
This might be a dumb question, but is there an easy way to get confidence intervals for the fitted values from `sma()`? I guess this is similar to, but not the same as, the `lower` and `upper` output from the prediction intervals.

**Comment by config-i1** [comment]
That's an interesting question. This functionality is not available in smooth functions by default (including `sma()`). But I think that this can be derived from the variance of the underlying state-space model. I speculate right now, but given that the fitted values correspond to one-step-ahead forecast, the variance for the fitted values should be:
`w' g s^2 g' w`
or in R:
```
ourModel <- sma(rnorm(100,100,10))
s2Fitted <- ourModel$measurement %*% ourModel$persistence * sigma(ourModel)^2 *
                   t(ourModel$persistence) %*% t(ourModel$measurement)
```

This variance can then be used for the calculation of the 95% confidence intervals as  `test$fitted - 1.96*sqrt(s2Fitted)` and `test$fitted + 1.96*sqrt(s2Fitted)`

But I am not 100% sure if the derivations are correct.

**Comment by shuckle16** [comment]
Awesome, thank you

**Comment by config-i1** [comment]
Glad to help!
