### ISSUE TITLE
auto.msarima() Switching back to non-intermittent model

### ISSUE THREAD

**Issue by mamut86** [config-i1/smooth#125]
In some cases it can be that there are not enough non-zero observations for the intermittent model building. it would help to have a fallback option which would run the model with the non-intermittent setting as it is done in es().

**Comment by config-i1** [comment]
This should now be fixed in 81f5bdcb5c54df9cb084d602862810d3be27c5c5 Can you, please, check?

**Comment by mamut86** [comment]
just tested and works well. Thanks
