### ISSUE TITLE
smoothCombine throws an error on example taken from the Reference manual

### ISSUE THREAD

**Issue by sbcalaff** [config-i1/smooth#142]
```
library("Mcomp")
models <- list(es(M3[[578]]), sma(M3[[578]]))
smoothCombine(M3[[578]],models=models)
```
Error:

> Error in UseMethod("smoothType") : 
>   no applicable method for 'smoothType' applied to an object of class "smooth"

"R version 3.6.1 (2019-07-05)"
`packageVersion(pkg = "smooth")`

> [1] ‘2.5.3’

$platform

> [1] "x86_64-w64-mingw32"

**Comment by config-i1** [comment]
Sorry, but I cannot reproduce it on R v3.6.1 with smooth v2.5.3. Everything works on my PC. Please, try reinstalling the package and restarting R. It glitches sometimes...

**Comment by sbcalaff** [comment]
Thank you for your prompt reply. The error continues to appear although I have reinstall smooth package again.

I have solved this issue with the next code:

> models <- list(es = es(M3[[578]]), sma = sma(M3[[578]]))
>   smoothCombine(M3[[578]],models=models)

Thank you again for your answers.

**Comment by config-i1** [comment]
Interesting. I don't understand why this fixes the issue, but I'm glad it worked :)
