### ISSUE TITLE
Tolerate time series of all zeros in auto.ces()

### ISSUE THREAD

**Issue by ArthurAndrews** [config-i1/smooth#146]
Thanks for the great package.  I find that auto.ces() will sometimes tolerate time series with all zeros, and sometimes not.  For example,

`auto.ces(ts(rep(0, 36), frequency = 12))` 

Will cause an error.  Respectfully, it's inconvenient to have to error trap the function when I apply it to many time series.  Thanks again.

**Comment by config-i1** [comment]
Thanks for reporting the bug! This is fixed now in the v2.6.0, which will be on CRAN later this week (you can also use devtools installation).
