### ISSUE TITLE
Error: 'Accuracy' is not an exported object from 'namespace:smooth'

### ISSUE THREAD

**Issue by Steviey** [config-i1/smooth#158]
Error: 'Accuracy' is not an exported object from 'namespace:smooth'
What can I do?

**Comment by config-i1** [comment]
Hi,

In what context does this error appear?

The function "Accuracy()" was moved to greybox in March 2019. It was then renamed to "measures()" in April 2019.

**Comment by Steviey** [comment]
Thank you config, for the answer. Well the context is pretty much the same as in the example of this documentation-page, which might have been updated due to it's prominent appearance on google... https://www.rdocumentation.org/packages/smooth/versions/2.4.7/topics/Accuracy

**Comment by config-i1** [comment]
Yes, that stuff refers to v2.4.7, while the latest is 3.0.1. So, no issue here.
Thanks! :)
