### ISSUE TITLE
Standard way to get a 'normal' RMSE

### ISSUE THREAD

**Issue by Steviey** [config-i1/smooth#159]
I know how to get error measurements from a forecast object...

`testRmse  <- greybox::measures(ts2,myFit$forecast,ts1,digits=5)`

Now I'm wondering, if there is a kind of standard procedure to get a "normal" RMSE
from a forecast object. I see errors and y in 'View(myForecast)'
Are these errors training errors and is y 'actual'?
How to get the 'normal' RMSE from that? I need that for comparisons.

**Comment by config-i1** [comment]
Hi,
So, this is not an issue, but rather a question about how to use the package. Please, send me an email, I'll help you out. You can find it here: https://github.com/config-i1/smooth/blob/master/DESCRIPTION
Cheers,
Ivan
