### ISSUE TITLE
Order selection mechanism in auto.adam() ARIMA

### ISSUE THREAD

**Issue by config-i1** [config-i1/smooth#161]
See if Sagaert & Svetunkov (2021) approach could be applied here based on ACF / PACF.

**Comment by config-i1** [comment]
A thing to add is the mechanism forbiding some combinations of ETS+ARIMA, switching to ARIMA instead of ETS in some cases, e.g. ETS(A,A,N)+ARIMA(0,2,3) => ARIMA(0,2,3).

**Comment by config-i1** [comment]
Possible algorithm:

1. Fit all iOrders with and without intercept.
2. Select the best iOrder based on AIC.
3. Analyse ACF, see if there are any seasonal MA. Fit the model, extract AIC.
4. Analyse PACF, see if there are any seasonal AR. Fit the model, extract AIC.
5. Go through 2 and 3 for all seasonals, starting from the furthest, ending with m=1, selecting the model that has the lowest AIC and improving upon it.
6. Select the best model based on 1 - 5

**Comment by Steviey** [comment]
Perhaps it would be nice, to let the user decide/switch, which method to use (internal/external). There are already some approaches out there. Then it would be easy, to do performance comparisons for individual cases too. Fabletools for example, has a order_constraint- feature, which could help to match the ADAM-criterias. As far as I understand, 'drift' has to be explicitly set and 'constant' can be excluded. I'm not really into the theoretically background of the different selection methods. I think, if there could be a difference in individual outcomes- it should be open for users. https://fable.tidyverts.org/reference/ARIMA.html

**Comment by config-i1** [comment]
Well, if there approaches out there, then why not use them? It would be a lot of work to implement them all in one function. I would prefer to develop just one most efficient and stick with it...

As for order constraint, this is done in adam by specifying the max arima lags via `orders=list(ar=c(3,2),i=c(2,1),ma=c(3,2))`.

**Comment by Steviey** [comment]
I see... It seems I have already implemented it, the right way (c(p,P),c(d,D),c(qQ)).
Do I have to change anything/keep in mind in regard to...'This only works with initial="backcasting"?

**Comment by config-i1** [comment]
Backcasting is an alternative way of initialising the states of the model. ARIMA works better with it in ADAM and it is more efficient on high frequency data. Just add `initial="backcasting"` in adam() to switch to it.

**Comment by config-i1** [comment]
Done in v3.1.0.41001.
