### ISSUE TITLE
smooth::auto.gum()...

### ISSUE THREAD

**Issue by Steviey** [config-i1/smooth#165]
Just FYI Ivan,

I tracked down the issue from https://github.com/config-i1/greybox/issues/49 and 
'Mat::operator(): index out of bounds' a little further. Turns out, it is directly related to an 'exogenous regressor' (properties below) and param 'type'. 

My exception skips the 'regressor' (don't know whether it would be correct, to name it regressor in this context) and switches to type='additive'. Switching only the type, seems to have no effect on the failing outcome. Hope this info is somehow useful.

![image](https://user-images.githubusercontent.com/3146082/104593804-873a4180-5670-11eb-8512-2418e1ef6818.png)

**Comment by config-i1** [comment]
This helps a bit, but a reproducible example (could be on artificial data using, for instance, rnorm() function) would help. The code that I could run and see, what happens.

**Comment by Steviey** [comment]
I could reproduce it with...

`y<-rnorm(561, mean=15, sd=5)
x<-c(
rep(0.00,144)
,rep(0.20,197)
,rep(0.40,158)
,rep(0.60,48)
,rep(0.80,11)
,rep(1.0,3)
)
data<-data.frame(x=x,y=y)
ts1<-ts(data=data[['y']],start=1,end=length(data[['y']]), frequency=1)
fitXregs <- as.data.frame(x,stringsAsFactors=F)

myFit <- smooth::auto.gum(ts1
	,lags           = frequency(ts1)
	,orders         = as.numeric(1)
	,type           = as.character('additive')
	,initial        = as.character('backcasting')
	,ic             = as.character('AIC')
	,loss           = as.character('MSE')
	,cumulative     = as.logical(TRUE)
	,interval       = as.character('none')
	,bounds         = as.character('none')
	,xregDo         = as.character('select')

	,holdout        = TRUE # erspart expliziten forecast!
	,h              = 1
	,silent         = 'none'
	,xreg           = fitXregs
)

**Comment by config-i1** [comment]
Thanks for the example, I've investigated it, and the issue is that the model explodes because `bounds="none"`. I've added the warning, pointing out that this might happen. In general, I'd advise using `bounds="admissible"` in `gum()`.
