### ISSUE TITLE
Distributions in ADAM

### ISSUE THREAD

**Issue by Steviey** [config-i1/smooth#167]
Hello!
Would it make sense, to have more distribution types for the error term of ADAM, for example gamma or weibull?

**Comment by config-i1** [comment]
Hi!
Gamma definitely, I know how to formulate the model with it and I will be implementing this in a next release.
As for Weibull, it's a bit more complicated, I'm not yet sure how to formulate the model in this case.

**Comment by Steviey** [comment]
This will be hot! I'm very excited. :-)

**Comment by config-i1** [comment]
On a related topic: Asymmetric Laplace doesn't work in ADAM for now, need to figure out how to do that correctly. Switched it off from v3.1.0

**Comment by Steviey** [comment]
Probably an exciting challenge. I wish I could transform formulas in code :-).

**Comment by config-i1** [comment]
Gamma is now implemented in 35d9f2bc46664ebea709bc34b59b193725e00430
Weibull, it will not be supported, because the mathematics involved in it is too complicated.
