### ISSUE TITLE
ADAM + greybox::ro() + .GlobalEnv [SOLVED]

### ISSUE THREAD

**Issue by Steviey** [config-i1/smooth#168]
_R version 4.0.2, smooth version 3.0.1_

Hello,

after updating to smooth 3.0.1, I can't get it running anymore, with greybox::ro(),... what is wrong?...
Code::
```
idx=120
y<-rnorm(idx, mean=15, sd=5)
x<-cbind(
	x1 =  rnorm(idx, mean=15, sd=5)
	,x2 =  rnorm(idx, mean=15, sd=5)
)    

fitXregs    <- data.frame(x=x,y=y,stringsAsFactors=F)
fitXregs    <- fitXregs %>% dplyr::relocate(y)

ourCall <- paste0("forecast(auto.adam(data=data
,model=",paste0("'",as.character('MAN'),"'"),"
,lags=",as.numeric(1),"
,ic=",paste0("'",as.character('AICc'),"'"),"
,regressors=",paste0("'",as.character('select'),"'"),"
,distribution=",paste0("'",as.character('dinvgauss'),"'"),"
,initial=",paste0("'",as.character(params$initial),"'"),"
,bounds=",paste0("'",as.character('usual'),"'"),"
,occurrence=",paste0("'",as.character('none'),"'"),"
,silent=",as.logical(FALSE),"
,orders=list(select=",as.logical(FALSE),")
), h=h, level=0.95, interval='prediction')")

ourVal      <-  c("mean")

error<-tryCatch({
	myFit<-  greybox::ro(fitXregs, h=1, origins=3, call=ourCall, value=ourVal, ci=TRUE)
	error<-0
}, warning = function(w) {
	print(w)
	return(1)
}, error = function(e) {
	print(e)
	return(1)
})

```
Error:
`<simpleError in attr(x, "tsp") <- c(1, NROW(x), 1): invalid time series parameters specified>`

**Comment by config-i1** [comment]
This is a very weird bug, somehow related to forecast function. This code doesn't work as well (it's easier, and a bit more appropriate, e.g. ro() assumes that we work with a vector in data):

>y<-rnorm(idx, mean=15, sd=5)
x<-cbind(
    x1 =  rnorm(idx, mean=15, sd=5)
    ,x2 =  rnorm(idx, mean=15, sd=5)
)
fitXregs    <- data.frame(y=y,x=x)
ourCall <- "forecast(adam(fitXregs[counti,],model='MAN',lags=1,regressors='select',distribution='dinvgauss'), newdata=fitXregs[counto,], h=h, level=0.95)"
ourVal <-  "mean"
myFit<-  ro(fitXregs$y, h=1, origins=3, call=ourCall, value=ourVal, ci=TRUE)

But changing the call to this (specific method) fixes it:
>ourCall <- "forecast.adam(adam(fitXregs[counti,],model='MAN',lags=1,regressors='select',distribution='dinvgauss'), newdata=fitXregs[counto,], h=h, level=0.95)"

I don't know why this happens. Could be a weird treatment of S3 class, but I don't see a reason for it.

Also, just to check, have you tried the latest github version of smooth, v3.0.2.41009?

**Comment by config-i1** [comment]
Okay. It seems to work on the latest version on github. Can you, please, check?

**Comment by Steviey** [comment]
I'm afraid this could take some time...

Install Option: "All":
Installing 34 packages: Rcpp, TTR, xts, quantmod, diffobj, rstudioapi, pkgbuild, waldo, ps, processx, jsonlite, callr, brio, colorspace, vctrs, pillar, magrittr, fansi, cli, R6, labeling, testthat, withr, tibble, rlang, isoband, digest, openssl, RcppArmadillo, tseries, lmtest, ggplot2, statmod, lamW
Error: Failed to install 'smooth' from GitHub:
(converted from warning) incomplete final line found on '/home/rstud/.Rprofile'

Install Option: "Cran only":
Installing 34 packages: Rcpp, TTR, xts, quantmod, diffobj, rstudioapi, pkgbuild, waldo, ps, processx, jsonlite, callr, brio, colorspace, vctrs, pillar, magrittr, fansi, cli, R6, labeling, testthat, withr, tibble, rlang, isoband, digest, openssl, RcppArmadillo, tseries, lmtest, ggplot2, statmod, lamW
Error: Failed to install 'smooth' from GitHub:
(converted from warning) incomplete final line found on '/home/rstud/.Rprofile'

Install Option: "none"
Installing 2 packages: waldo, brio
Error: Failed to install 'smooth' from GitHub:
(converted from warning) incomplete final line found on '/home/rstud/.Rprofile'

**Comment by Steviey** [comment]
Hm, can you point out the notation of counti/counto a little bit?...

```
fitXregs    <- data.frame(x=x,y=y,stringsAsFactors=F)
        fitXregs    <- fitXregs %>% dplyr::relocate(y)
        train <-fitXregs[1:80,]
        test  <-fitXregs[81:120,]
        
        ourCall <- paste0("forecast(auto.adam(fitXregs[1:80,]
        ,model=",paste0("'",as.character('MAN'),"'"),"
        ,lags=",as.numeric(1),"
        ,ic=",paste0("'",as.character('AICc'),"'"),"
        ,regressors=",paste0("'",as.character('select'),"'"),"
        ,distribution=",paste0("'",as.character('dinvgauss'),"'"),"
        ,initial=",paste0("'",as.character(params$initial),"'"),"
        ,bounds=",paste0("'",as.character('usual'),"'"),"
        ,occurrence=",paste0("'",as.character('none'),"'"),"
        ,silent=",as.logical(FALSE),"
        ,orders=list(select=",as.logical(FALSE),")
        ),newdata=fitXregs[81:120,],h=h, level=0.95)")
        
        ourVal      <-  c("mean")
    
        error<-tryCatch({
            myFit<-  greybox::ro(fitXregs$y, h=1, origins=3, call=ourCall, value=ourVal, ci=TRUE)
            error<-0
        }, warning = function(w) {
            print(w)
            return(1)
        }, error = function(e) {
            print(e)
            return(1)
        })

```
Error:
```
<simpleError in is.adam.sim(data): object 'fitXregs' not found>
<simpleError in is.adam.sim(data): object 'fitXregs' not found>
```

**Comment by config-i1** [comment]
I've checked this on a couple of PCs, and the code above works with "forecast" instead of "forecast.adam" on smooth v3.0.2.41009 and greybox v0.6.7.41002, when I specify initial="optimal" (I don't have params, and it should only be either "optimal" or "backcasting" in auto.adam).

As for counti and counto, they are not explained explicitly, but they are described both in examples of ro() and in the vignette. I should probably add them in the description of the parameters of the function. Point taken.

**Comment by Steviey** [comment]
_Ubuntu 16.x, R version 4.0.2, smooth version 3.0.2.41009 (dev), greybox 0.6.7.41002_
Strange... I updated greybox and all its dependencies too.
The same code with mehtod: 'forecast' gives me: 
`<simpleError in is.adam.sim(data): object 'fitXregs' not found>`

**Comment by config-i1** [comment]
Just a suggestion, why not simplify the code first and see if it works (this should be equivalent to yours):

```{r}
idx=120
y<-rnorm(idx, mean=15, sd=5)
x<-cbind(
	x1 =  rnorm(idx, mean=15, sd=5)
	,x2 =  rnorm(idx, mean=15, sd=5)
)
fitXregs    <- data.frame(y=y,x=x,stringsAsFactors=F)

ourCall <- "forecast(adam(fitXregs[counti,],model='MAN',lags=1,ic='AICc',
regressors='select',distribution='dinvgauss',initial='optimal',bounds='usual',
occurrence='none',silent=FALSE,orders=list(select=FALSE)),
newdata=fitXregs[counto,],h=h, level=0.95)"

ourVal <- "mean"

myFit<-  greybox::ro(fitXregs$y, h=1, origins=3, call=ourCall, value=ourVal, ci=TRUE)
```

This works on my PC (Kubuntu 20.04). See if this works for you. If it does, maybe there are some typos in the original one.

Also, make sure that "y" doesn't contain negative values - Inverse Gaussian doesn't work with them.

In addition, I would recommend switching silent to TRUE for ro(), otherwise it will start plotting tones of figures.

Finally, you don't need to provide all the default parameters, so the call can be simplified to:

`ourCall <- "forecast(adam(fitXregs[counti,], model='MAN', regressors='select', distribution='dinvgauss'),
newdata=fitXregs[counto,], h=h, level=0.95)"`

**Comment by Steviey** [comment]
My guess is, that it has to do with: 'In this case we just need to make sure that the Global Environment contains the xreg data frame.' Honestly, if I look in the Global Environment tab of RStudio, I see no fitXreg variable. Until now I thought it will be automatically registered there. But I have to mention, that my script weights more then 3 MB and there is a ton of stuff already registered in the Global Environment.

**Comment by config-i1** [comment]
This is really weird. When you create a variable via `fitXregs    <- data.frame(x=x,y=y,stringsAsFactors=F)`, it is automatically created in the Global Environment. Could this be something that `dplyr::relocate(y)` does?

**Comment by Steviey** [comment]
I have no evidence of such a behavior of dplyr (double checked).
