### ISSUE TITLE
accuracy for the training set after auto.msarima

### ISSUE THREAD

**Issue by SkyStreet** [config-i1/smooth#177]
This is not a bug report (I've done some searching in google and stackexchange but no luck). I am now using the _auto.msarima_ in the smooth package, however I find that the accuracy the function returned focused on the holdout sample, i.e. the forecast, the testing set, in my view. But I'd also like to know the accuracy of the training set. There does have _s2_ value (variance of the residuals). When I apply forecast and forecast::acucuracy, like I usually do in arima or tbats situation, there comes the error: _Error in NextMethod(.Generic) : cannot assign 'tsp' to zero-length vector_. 
Is there anything more I could do to return the accuracy of the training set or I just missed the point and misunderstood?

**Comment by config-i1** [comment]
You are correct, smooth functions only report the holdout sample performance of models. This is because the in-sample one is typically not useful.
Another thing is that `accuracy()` method is not supported by smooth functions and I don't plan on implementing it. But there is a `measure()` function from `greybox` that you can use to get several measures for the provided holdout, forecasts and actuals. You can substitute holdout and forecasts by respective in-sample actuals and fitted values, and get a set of error measures.

**Comment by SkyStreet** [comment]
> You are correct, smooth functions only report the holdout sample performance of models. This is because the in-sample one is typically not useful.
> Another thing is that `accuracy()` method is not supported by smooth functions and I don't plan on implementing it. But there is a `measure()` function from `greybox` that you can use to get several measures for the provided holdout, forecasts and actuals. You can substitute holdout and forecasts by respective in-sample actuals and fitted values, and get a set of error measures.

Thanks for the tip. Well, now a bit confused by the arguments in _measures()_ function, I thought the input _holdout_ and _actual_ are the same in my attempt? However in the _acuuracy_  given by _msarima_ (I assume _accuracy_ is calculated through _measures()_), those above two should be different, respectively the holdout(actual value of the test) and the value of the training, and the _actual_ is for the relative errors calculation? So far so good?

**Comment by config-i1** [comment]
That really depends on what you want to measure. If you want the in-sample performance, then your `actuals` will be the same as the `holdout`. If you are interested in the holdout performance, they will differ.

**Comment by SkyStreet** [comment]
Perfectly solved. Thanks.
