### ISSUE TITLE
Predefined persistence vector can only be used with preselected ETS model

### ISSUE THREAD

**Issue by Steviey** [config-i1/smooth#190]
I'm currently trying smooth non-native- with modeltime-tidymodels via exp_smooth()....

https://business-science.github.io/modeltime/reference/exp_smoothing.html

While training the alpha and beta params via smooth_level() and smooth_trend() I get the following message:

`Predefined persistence vector can only be used with preselected ETS model`

I also notice no metrics-improvements while training.

![image](https://user-images.githubusercontent.com/3146082/148430608-52fff778-a020-4fa0-b34e-10e4a611b465.png)

What could this mean, in the smooth/tidymodels-context?

**Comment by config-i1** [comment]
I haven't used modeltime-tidymodels, so I don't know how they call the functions. But this warning typically appears, when the model is not selected. So, I'm speculating that you also need to provide `model="ANN"` or whatever model you want to use.

**Comment by Steviey** [comment]
Thank you Ivan, this was my first idea too. But then we have a doubled declaration of param "model". I have to ask Matt (modeltime) for this.

**Comment by Steviey** [comment]
... my fault....

```
model_spec_exp <- exp_smoothing(
	 error     = as.character(fitSetupList[['error']])
	,trend     = as.character(fitSetupList[['trend']])
	,season    = as.character(fitSetupList[['season']])
	#,damping   = as.character(fitSetupList[['damping']])
	,smooth_level   = as.numeric(resObj$bestParams$smooth_level)
	,smooth_trend  = as.numeric(resObj$bestParams$smooth_trend)
) %>%
set_engine("smooth_es",holdout=FALSE)
```
