### ISSUE TITLE
Hello initparams

### ISSUE THREAD

**Issue by Steviey** [config-i1/smooth#192]
R latest, smooth latest

Hello,

is this something, I should be aware of?...

`Error in initparams(Etype, Ttype, Stype, dataFreq, obsInSample, obsAll, : Not compatible with requested type: [type=character; target=double].
`

**Comment by config-i1** [comment]
Hi,

I'm not sure. Can you give me a reproducible example?

**Comment by Steviey** [comment]
Hi Ivan,

it's highly abstracted tidymodels/modeltime-ensemble-code. 
I' m currently focusing on state space models, integrated in avg/median/weighted and stacked- ensembles together with ML algos and meta-learners. 

Basically I try to grid-search parameters of the es-model of smooth. 
I want to define very very big search spaces for the key params.

The challenge is, to make sure modeltime communicates/translates unified params, the right way to smooth. So I don't know what is meant by initparams. If I know it, I can search, if  there is a chance to tweak it along the tidyverse.    

As you know, I have an extensive standalone version of smooth incl. grid search and xRegs already running. The ensemble-approach is another experiment- trying to combine my best ML-algos with ets and others. :-)

`algoTrainCase   <-'gridLatin'
ret$modelObj    <- exp_smoothing(
	error          = tune()
	,trend         = tune()
	,season        = tune()
	,damping       = tune()
	,smooth_level  = tune()
	,smooth_trend  = tune()
) %>%
set_engine("smooth_es",holdout=FALSE) #,model =as.character(trainSetupList[['model']])
ret$finalParams <- ret$modelObj %>% parameters() #%>% finalize(x=trainPart)
# Optional, wenn noetig, erst wenn alle xRegs komplett sind, 
# oder wenn bestimmte param-ranges zwingend angepasst werden muessen, z.b. sample_size
ret$finalParams <- updateMyParams(ret$finalParams,subModel,taskSwitch,trainSetupList)
`

**Comment by config-i1** [comment]
`initparams()` is an internal function written in C++ to process the input parameters in ETS and create the matrices for the state space model. The user typically doesn't have access to these. If an error occurs with this, then there is either something wrong with the function or with the call to `es()`.

**Comment by Steviey** [comment]
**Interesting,** I will observe it further.
In general I can say, smooth-ets incl. xregs works as submodel in a modeltime-ensemble. But I have no idea, if it works as intended :-).
I had to implement some fall-back-param-combinations to avoid code-breaks. Measurements are looking 'normal'.

**Comment by Steviey** [comment]
**Update:** Since I can replecate the error now, it seems to be related to the call to es(). The third-party functions doing this, are here... https://business-science.github.io/modeltime/reference/exp_smoothing.html
To avoid the error, we have to choose the right call.
If we choose always a wrong call while training, we should have one as fall back which never fails to avoid code breaks.

**Comment by config-i1** [comment]
I guess that this then relates to the third-party function, not to `es()`. If you have a specific command for es() that produces an error, I can look into it to make it more robust and return something.

**Comment by Steviey** [comment]
Yes, it is a third party problem. I think the calls are constructed, like they would be made by us manually, according to your documentation. You know some definitions could make no sense, depending on the individual data structure. Since modeltime-ensemble does not care about failed model fits/builds while training, it will always break the code, regardless of the output of smooth (warnings and errors). This kind of stuff has to be handled by the user. The text above is a strategy to get around it while training. :-) Unfortunately we can only display pre-selected model-definitions and successful definitions, not explicitly failed definitions (you could do so in your error-messages- they will be routed to the screen via the verbosity-settings of tune_grid()). 
![image](https://user-images.githubusercontent.com/3146082/151216706-c5f240db-41a2-4279-ba8b-c207d7af2996.png)

**Comment by Steviey** [comment]
There is some more output, I have to investigate, but some models make there way to the ensemble...

![image](https://user-images.githubusercontent.com/3146082/151225250-223bffd3-6c0e-419b-b97e-0f16a6725464.png)

**Comment by Steviey** [comment]
Trying to make a grid, that makes sense in regard to both, smooth and modeltime ...
![image](https://user-images.githubusercontent.com/3146082/151487373-0a7111a6-0640-4092-910f-cff12bdadd7a.png)

`persistenceGrid <- grid_max_entropy(
	smooth_trend()
	,smooth_level()
	,smooth_seasonal()
	,size = 10
)

smoothEtsGrid <- expand.grid(
	error=c("auto","additive","multiplicative")
	,trend=c("auto","additive","multiplicative","additive_damped","multiplicative_damped","none")
	,season=c("auto","additive","multiplicative","none")
)

finalGrid   <- tidyr::crossing(persistenceGrid,smoothEtsGrid,.name_repair="minimal")
finalGrid   <- finalGrid %>% dplyr::mutate(modelDef = paste0(error,'_',trend,'_',season))

finalGrid   <- finalGrid %>% dplyr::mutate(smooth_level = case_when(
	error=='none' ~ as.numeric(NA)
	,error=='auto' ~ as.numeric(NA)
	,TRUE ~ smooth_level
))
finalGrid   <- finalGrid %>% dplyr::mutate(smooth_trend = case_when(
	trend=='none' ~ as.numeric(NA)
	,trend=='auto' ~ as.numeric(NA)
	,TRUE ~ smooth_trend
))
finalGrid   <- finalGrid %>% dplyr::mutate(smooth_seasonal = case_when(
	season=='none' ~ as.numeric(NA)
	,season=='auto' ~ as.numeric(NA)
	,TRUE ~ smooth_seasonal
))

print(class(finalGrid))
View(finalGrid)
stop()
`

**Comment by Steviey** [comment]
**Update:** damping-Fix works...but this is my first PR since the ending of WWII. I forgot to much Github-stuff. ;-).

**Comment by Steviey** [comment]
Some things I noticed (Part II):

- It seems to be a good idea, to filter 'allowed' model definitions, before training on individual time series.

![image](https://user-images.githubusercontent.com/3146082/151683976-e44e4ac8-046e-4abd-8cec-8e7e3edf9afb.png)

https://rpubs.com/JiahaoLin/639763
