### ISSUE TITLE
[[hint]] silent=FALSE

### ISSUE THREAD

**Issue by Steviey** [config-i1/smooth#193]
Hello,
I get different model-graphs with the same data and model-definitions in adam, auto_adam and smooth::es() when setting silent=FALSE. Is this normal, and what do the x-axes of the plots represent?

![image](https://user-images.githubusercontent.com/3146082/152095122-86914a83-e806-4775-9850-96ec3a4da511.png)

![image](https://user-images.githubusercontent.com/3146082/152095171-27babeae-4487-4f71-a79c-23dce0365ad9.png)

![image](https://user-images.githubusercontent.com/3146082/152095217-ee6fbe55-458f-4fa6-9e22-9c3482f82f00.png)

```
model_spec  <- adam_reg(
                    ets_model='ANN'
                    
                ) %>%
                    set_engine("adam",silent=FALSE)
                    model_spec<-parsnip::eval_args(model_spec)

                    set.seed(123)
                    wflw_fit<- workflow() %>%
                        add_model(model_spec) %>%
                        add_recipe(recipe_spec) %>%
                        fit(df_train)
                    
                    model_spec1  <- exp_smoothing(
                        error            = 'additive'
                        ,trend           = 'none'
                        ,season          = 'none'    
                    ) %>%
                    set_engine("smooth_es",holdout=FALSE,silent=FALSE)
                    model_spec1<-parsnip::eval_args(model_spec1)

                    set.seed(123)
                    wflw_fit<- workflow() %>%
                        add_model(model_spec1) %>%
                        add_recipe(recipe_spec) %>%
                        fit(df_train)

                    model_spec2  <- adam_reg(
                        ets_model='ANN'
                    ) %>%
                    set_engine("auto_adam",silent=FALSE)
                    model_spec<-parsnip::eval_args(model_spec2)

                    
                    set.seed(123)
                    wflw_fit<- workflow() %>%
                        add_model(model_spec2) %>%
                        add_recipe(recipe_spec) %>%
                        fit(df_train)
```
I also get this graph fitting ADAM, while cross validation for loss-function. What does the x on the left side mean?
![image](https://user-images.githubusercontent.com/3146082/152194620-fa9370bd-a947-4db2-b960-bb3d24bbbf1d.png)

**Comment by config-i1** [comment]
Looks like an issues with classes. Can you please provide a reproducible example (always do that if you can)?

**Comment by Steviey** [comment]
OK Ivan, I will try it. The problem is, modeltime needs a date column. I will search a way to introduce them in this...

`# dummy reproduceable example
y<-rnorm(561, mean=15, sd=5)
x<-c(
   rep(0.00,144)
   ,rep(0.20,197)
   ,rep(0.40,158)
   ,rep(0.60,48)
   ,rep(0.80,11)
   ,rep(1.0,3)
   )
data<-data.frame(x=x,y=y)
ts1<-ts(data=data[['y']],start=1,end=length(data[['y']]), frequency=1)
fitXregs <- as.data.frame(x,stringsAsFactors=F)`

**Comment by Steviey** [comment]
holdout...
```
model_spec  <- exp_smoothing(
        error           = 'additive'
        ,trend           = 'none'
        ,season          = 'none'    
        # ,damping          = 1   
        # ,smooth_level     = 1
        # ,smooth_trend    = param6
        # ,smooth_seasonal = param7
    ) %>%
    set_engine("smooth_es",holdout=TRUE,silent=FALSE)
    model_spec<-parsnip::eval_args(model_spec)
```

**Comment by Steviey** [comment]
Can't reproduce it native.

**Comment by Steviey** [comment]
```

idx=120
    y<-rnorm(idx, mean=15, sd=5)
    x<-cbind(
        x1 =  rnorm(idx, mean=15, sd=5)
        ,x2 =  rnorm(idx, mean=15, sd=5)
    )    

    fitXregs    <- data.frame(x=x,y=y,stringsAsFactors=F)
    fitXregs    <- fitXregs %>% dplyr::relocate(y)
    myModel <- adam(fitXregs,"ANN",silent=FALSE,h=1,holdout=TRUE)
 ```

**Comment by config-i1** [comment]
Are you using the most recent version of the package? I cannot reproduce this. Here is what I get for the first part of your code:
![image](https://user-images.githubusercontent.com/7396330/152693111-3b09266b-1b0d-473b-969a-36058971134a.png)

**Comment by Steviey** [comment]
I noticed yesterday, that my local versions are way to old. I am working on multiple instances, sorry.

**Comment by Steviey** [comment]
**_Windows 7, greybox 1.0.5.41001, smooth 3.1.6.41004, R version 4.0.5_**
I get the following:
```

idx=120
    y<-rnorm(idx, mean=15, sd=5)
    x<-cbind(
        x1 =  rnorm(idx, mean=15, sd=5)
        ,x2 =  rnorm(idx, mean=15, sd=5)
    )    

    fitXregs    <- data.frame(x=x,y=y,stringsAsFactors=F)
    fitXregs    <- fitXregs %>% dplyr::relocate(y)
    myModel <- adam(fitXregs,"ANN",silent=FALSE,h=10,holdout=TRUE)
```

![image](https://user-images.githubusercontent.com/3146082/152719528-aca6402c-9094-4ae0-8ca0-dc1ec490397a.png)

```
idx=120
    y<-rnorm(idx, mean=15, sd=5)
    x<-cbind(
        x1 =  rnorm(idx, mean=15, sd=5)
        ,x2 =  rnorm(idx, mean=15, sd=5)
    )    

    fitXregs    <- data.frame(x=x,y=y,stringsAsFactors=F)
    fitXregs    <- fitXregs %>% dplyr::relocate(y)
    myModel <- adam(fitXregs,"ANN",silent=FALSE,h=1,holdout=TRUE)
```

![image](https://user-images.githubusercontent.com/3146082/152719612-484933bd-a3c2-4b37-8df6-b702df7ecc50.png)

**Comment by config-i1** [comment]
The same code can be simplified to (for reproducibility purposes, so that I do not need to load tidyverse packages):

```
idx <- 120
x<-cbind(
    y = rnorm(idx, mean=15, sd=5),
    x1 =  rnorm(idx, mean=15, sd=5),
    x2 =  rnorm(idx, mean=15, sd=5)
)

fitXregs    <- as.data.frame(x, stringsAsFactors=F)
myModel <- adam(fitXregs,"ANN",silent=FALSE,h=10,holdout=TRUE)
```

But this is what I get:
![image](https://user-images.githubusercontent.com/7396330/152824106-76b95b80-a475-4261-b0ea-7e7febaa9d52.png)

And this is with `h=1`:
![image](https://user-images.githubusercontent.com/7396330/152824188-16bfe328-db27-4408-bb4a-c9870910b170.png)

So, I still cannot reproduce this.

**Comment by config-i1** [comment]
I assume that this can be closed now.

**Comment by Steviey** [comment]
Must be environment related.
