### ISSUE TITLE
How can I check the length of dimnames?

### ISSUE THREAD

**Issue by Steviey** [config-i1/smooth#197]
**tidymodels, not native**

I know I have seen this error a couple of times. But I can't remember how I fixed it....
It seems to have something to do with line 780 in...

https://github.com/config-i1/smooth/blob/master/R/adam.R

How can I check the length of the components?

```
Error in matrix(NA, componentsNumberETS + componentsNumberARIMA + xregNumber +  : 
length of 'dimnames' [1] not equal to array extent

Error in matrix(NA, componentsNumberETS + componentsNumberARIMA + xregNumber +  : 
  length of 'dimnames' [1] not equal to array extent
In addition: There were 14 warnings (use warnings() to see them)
     ▆
  1. ├─base::do.call(doModelPlots, list()) at R/adthocStrat/ensShell.R:297:0
  2. ├─global `<fn>`()
  3. │ └─wflw %>% fit(allData) at R/adthocStrat/ensShell.R:284:8
  4. ├─generics::fit(., allData)
  5. ├─workflows:::fit.workflow(., allData)
  6. │ └─workflows::.fit_model(workflow, control)
  7. │   ├─generics::fit(action_model, workflow = workflow, control = control)
  8. │   └─workflows:::fit.action_model(...)
  9. │     └─workflows:::fit_from_xy(spec, mold, control_parsnip)
 10. │       ├─generics::fit_xy(...)
 11. │       └─parsnip::fit_xy.model_spec(...)
 12. │         └─parsnip:::xy_xy(...)
 13. │           ├─base::system.time(...)
 14. │           └─parsnip:::eval_mod(...)
 15. │             └─rlang::eval_tidy(e, ...)
 16. ├─modeltime::adam_fit_impl(...)
 17. │ └─rlang::eval_tidy(fit_call)
 18. ├─smooth::adam(...)
 19. │ └─smooth estimator(...)
 20. │   └─smooth creator(...)
 21. │     └─base::matrix(...)
 22. └─global `<fn>`()
 23.   └─lobstr::cst() 
```

Someone remember?

https://stackoverflow.com/questions/12985653/what-does-length-of-dimnames-1-not-equal-to-array-extent-mean

**Noticed:** The error disappears, if I modify the threshold for correlating predictors....
`step_corr(all_numeric(), -all_outcomes()"), threshold = 0.10) `

This let me think, it's related to input-data. So no real bug.
I can't provide live-data.

**Comment by config-i1** [comment]
Please provide simple reproducible example. I cannot do anything unless I can reproduce it. There can be many reasons why that error appeared, pointing to the specific line doesn't help.
