### ISSUE TITLE
Issues with plotting when running in parallel on Mac OSX

### ISSUE THREAD

**Issue by wellermatt** [config-i1/smooth#28]
Running the `es` function in parallel with `foreach` or `mclapply` produces unexpected results on OSX.  Further investigation shows that the graphical output within the function is causing the problem and `silent=TRUE` fixes it.

I'd suggest that a user running in parallel might wish to suppress only the graphical element to avoid the quartz issue but retain some of the output to the console.

My suggestion is to add parameters `silent.text` and `silent.graphics` accepting `TRUE` or `FALSE` or `silent = c('all','graphics')` so the user has control to just switch the graphics off.

> Some unstable behaviour has also been encountered on Mac OS X whenever the parallel computations are run in a session where the quartz device for plotting has been used previously. Though non of the parallel parts uses on screen devices, the unstable behaviour has only been encountered when the quartz device has been used in the session, and a note is printed when the parallel backend is registered and the quartz device is the current device.

[See here](http://www.inside-r.org/packages/cran/ppstat/docs/getRegisteredParBackend)

**Comment by config-i1** [comment]
Done in v1.0. Now silent accepts c("none","all","graph","legend","output") and c(TRUE,FALSE).
