### ISSUE TITLE
Issue with ssarima specification

### ISSUE THREAD

**Issue by trnnick** [config-i1/smooth#32]
Run the following:
library(TStools)
ssarima(referrals,ar.orders=0,i.orders=0,ma.orders=0,lags=1,intervals=FALSE,FI=FALSE,holdout=FALSE,h=h,silent=TRUE)

it doesn't like that I ask for an ARIMA(0,0,0) and I get
Error in rep(0, n.components - 1) : invalid 'times' argument

Also it would make sense to have the calculation of t+h errors optional. I want to scale this up!

**Comment by config-i1** [comment]
This is related to the issue #26. So closing as a duplicate :P
