### ISSUE TITLE
Issue with ssarima specification - The return of the bug!

### ISSUE THREAD

**Issue by trnnick** [config-i1/smooth#40]
I run this:
ssarima(AirPassengers,ar.orders=0,i.orders=0,ma.orders=0,constant=TRUE)
I get this:
Error during wrapup: not compatible with requested type
Can I get this?
forecast accuracy: 100%, go home all your problems are solved!

I run this:
ssarima(AirPassengers,ar.orders=0,i.orders=0,ma.orders=0)
I get this:
Error: What do you want me to do? You have not defined any model!
Called from: ssarima(AirPassengers, ar.orders = 0, i.orders = 0, ma.orders = 0)
Can I instead get this?
Warning, zero order model, constant forced

**Comment by config-i1** [comment]
The first one runs perfectly in the last version of smooth on my PC.

The second stuff is easy to implement, so see the recent update of smooth.

**Comment by trnnick** [comment]
Even if it runs perfectly, it does not give me the go home all your problems are solved output!I does not run for me though, let me reinstall things

**Comment by config-i1** [comment]
This is peculiar. I would try deleting smooth via Rstudio and then removing the folder manually from your hard drive. Then reinstall...
I've never encountered such problems myself though...

**Comment by trnnick** [comment]
We did exactly the same the last time... there must be something that is bothering it. I'll figure it out

**Comment by config-i1** [comment]
By the way, I usually firstly detach smooth in Rstudio before updating it from github. Maybe if you don't some functions are not updated for some reason...
