### ISSUE TITLE
Issues when using an estimated es model when !is.null(xreg)

### ISSUE THREAD

**Issue by trnnick** [config-i1/smooth#59]
I paste here a script that will allow you to reproduce the various issues (bugs!) with comments why I think they are problematic and how potentially could be solved. There all come from trying to produce in-sample rolling origin forecasts.

> library(smooth)

Create example time series
> y <- sim.es("ANN",frequency=12,persistence=0.2,initial=1000,obs=160,mean=0,sd=100)$data
> y[27] <- y[27] * 2
> y[45] <- y[45] * 2
> plot(y)

Create dummies
> x.1 <- x.2 <- rep(0,180)
> x.1[27] <- 1
> x.2[45] <- 1
> x.2[c(165,175)] <- 1

Fit model
> es(y, xreg=cbind(x.1,x.2))

This gives an error, which makes limited sense. X should be allowed to be longer than y, or y+hrz.
I know that lm and many other functions give similar errors, but they are not built for forecasting!
Also the user should know at a very basic level what she/he is doing, if not then...

Lets accomondate the model
>fit <- es(y, h=20, xreg=cbind(x.1,x.2))

Now I will make an in-sample rolling origin sort of forecast
> es(ts(y[1:24],freq=12),model=fit, cbind(x.1,x.2)[1:24,])

Both dummies are zero, so es removes them, but still expects xreg
The same error happens when
>es(ts(y[1:24],freq=12),model=fit)

In this case the error is rightly given! In the previous case there is no reason
Everything is estimated and when the X effect is calculated is zero, so no problem.

Here is another case that is similar
> es(ts(y[1:36],freq=12),model=fit, cbind(x.1,x.2)[1:36,])

I get an error... I can fix that by doing
> fit.2 <- fit
> fit.2$xreg <- cbind(x.1,x.2)[1:36,]
> es(ts(y[1:36],freq=12),model=fit.2, cbind(x.1,x.2)[1:36,])

Now I get a different error. This happens because one of the two variables
Has 0 variance, so it is removed and now the xreg number of variables does not
match initialX, so problem... still it should not make a difference, as everything
is already estimated

Another example
> es(ts(y[1:48],freq=12),model=fit, cbind(x.1,x.2)[1:48,])

I get the error about xreg size (different from what was used for the estimation)
Let me override that
>fit.2 <- fit
>it.2$xreg <- cbind(x.1,x.2)[1:48,]
>es(ts(y[1:48],freq=12),model=fit.2, cbind(x.1,x.2)[1:48,])

This works! Because both xreg contain information, so everything is retained
But as I argued before, none of the above cases should be problematic, as 
there is no estimation done in the first place!!!

So I think if you retain the check for the number of variables == length(initialX)
that is the only one you need when an estimated model is already given!

Enjoy!

**Comment by config-i1** [comment]
Should be fixed in v1.4.7
