### ISSUE TITLE
sim.arima - issue with rnorm

### ISSUE THREAD

**Issue by trnnick** [config-i1/smooth#63]
I run this: sim.ssarima(ar.orders=1,i.orders=0,ma.orders=1,frequency=12,obs=1220,silent=TRUE,mean=0,sd=50)

I get this error: Error in rnorm(n = 1221, TRUE, 0, 50) : unused argument (50)
I check rnorm inputs and they are: rnorm(n, mean = 0, sd = 1), so there is an extra argument in sim.arima!

**Comment by config-i1** [comment]
This is because silent is now redundant parameter. Remove it and it will work.
