### ISSUE TITLE
make silent=TRUE default

### ISSUE THREAD

**Issue by trnnick** [config-i1/smooth#75]
I think that makes more sense as a default value

**Comment by config-i1** [comment]
Do I understand correctly that you want my function to shut up by default? :)

**Comment by trnnick** [comment]
Indeed! They can be very noisy if you have a lot of them running... it disturbes my "relaxing" music!

**Comment by config-i1** [comment]
I'm not sure about that. I like how it talks with me. We should ask some one else's opinion. I'll make a survey :)

**Comment by config-i1** [comment]
Done in aa0be9d3652ec61d731632852976d4787013ce14
