### ISSUE TITLE
compilation/link problem with ‘smooth’ package

### ISSUE THREAD

**Issue by mxmq** [config-i1/smooth#85]
Greetings,

I'm an R user and just tried devtools::install_github(“config-i1/smooth”) but there is a compilation/link problem with ‘smooth’ (whereas mapa compiled/loaded successfully). The reason seems to be that the ld command references a local directory not present at my system.

Can this option be modified so as (perhaps) not to reference this specific path/version but to let the compiler system choose some default?

Many thanks.

ld: warning: directory not found for option ‘-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2’
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [smooth.so] Error 1
ERROR: compilation failed for package ‘smooth’

**Comment by config-i1** [comment]
Hi!
I do not set or change any paths for the libraries in smooth. It looks like a MacOS problem, which is discussed here: http://www.thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/ (you can also see this link in the Notes section of the smooth package on github).

**Comment by mxmq** [comment]
Many thanks for your response and the link. The problem was resolved following the instructions therein.

**Comment by config-i1** [comment]
Great!
